version: "2"
run:
  modules-download-mode: readonly
  tests: true
output:
  path-prefix: ""
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - decorder
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - goconst
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    decorder:
      dec-order:
        - const
        - var
        - func
      disable-dec-order-check: true
      disable-init-func-first-check: false
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    goconst:
      min-len: 3
      min-occurrences: 3
    govet:
      disable:
        - inline
    godot:
      scope: all
      exclude:
        - '^fixme:'
        - '^todo:'
      capital: true
      period: true
    gosec:
      excludes:
        - G101
        - G112
        - G115
        - G710
      severity: low
      confidence: low
    lll:
      line-length: 150
      tab-width: 1
    makezero:
      always: false
    misspell:
      locale: US
    nakedret:
      max-func-lines: 60
    revive:
      rules:
        - name: var-naming
          arguments:
            - - HTTP
              - ID
              - TLS
              - TCP
              - UDP
              - API
              - CA
              - URL
              - DNS
          disabled: true
    staticcheck:
      checks:
        - all
        - -SA1019
        - -SA2002
        - -SA5008
        - -ST1003
    unparam:
      check-exported: false
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: true
      exported-fields-are-used: true
      parameters-are-used: true
      local-variables-are-used: true
      generated-is-used: true
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - funlen
          - goconst
          - gosec
          - lll
          - makezero
          - rowserrcheck
          - wsl
        path: _test\.go
    paths:
      - doc\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
